### ISSUE TITLE
Actually not working and shows below error

### ISSUE THREAD

**Issue by megabites2013** [christian-fei/twitter-oauth-login-in-nodejs#5]
(node:58058) UnhandledPromiseRejectionWarning: Error: Error getting OAuth request token
    at /Users/sebamac/projects/twitter-oauth-login-in-nodejs/oauth-utilities.js:37:18
    at /Users/sebamac/projects/twitter-oauth-login-in-nodejs/node_modules/oauth/lib/oauth.js:543:17
    at passBackControl (/Users/sebamac/projects/twitter-oauth-login-in-nodejs/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/Users/sebamac/projects/twitter-oauth-login-in-nodejs/node_modules/oauth/lib/oauth.js:409:9)
    at IncomingMessage.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:58058) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by asyncjason** [comment]
make sure you are using your app's API Key and Secret. Not the Client ID and Secret.
